---
title: "Cleaning data for 512 project"
author: "Clara Richter"
date: "3/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r support, warning=FALSE,message=FALSE,include=FALSE}
library(kableExtra)
library(stargazer)
library(dplyr)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(naniar)
```

```{r}
gayMarriage <- read.csv(file = "same-sex-marriage-recognition.csv", header = T,stringsAsFactors = T)

births_outside_marriage <- read.csv(file = "share-of-births-outside-marriage.csv", header = T,stringsAsFactors = T)

marriageRate <- read.csv(file = "marriage-rate-per-1000-inhabitants.csv", header = T,stringsAsFactors = T)
```

```{r}
# remove code column

gayMarriage <- subset(gayMarriage, select = -c(2))

births_outside_marriage <- subset(births_outside_marriage, select = -c(2))

marriageRate <- subset(marriageRate, select = -c(2))

names(gayMarriage) <- c('Country', 'Year', 'Same_Sex_Marriage')
names(births_outside_marriage) <- c('Country', 'Year', '%Births_Outside_Marriage')
names(marriageRate) <- c('Country', 'Year', 'Marriage_Rate')
```

```{r}
gayMarriage <- data.frame(lapply(gayMarriage, function(x) {gsub("Same-sex marriage legal", "legal", x)}))

gayMarriage <- data.frame(lapply(gayMarriage, function(x) {gsub("Same-sex marriage not legally recognized", "not legal", x)}))

gayMarriage <- data.frame(lapply(gayMarriage, function(x) {gsub("Some rights to same-sex couples", "some rights", x)}))

gayMarriage <- data.frame(lapply(gayMarriage, function(x) {gsub("legal in some jurisdictions", "some rights", x)}))


gayMarriage$Same_Sex_Marriage <- as.factor(gayMarriage$Same_Sex_Marriage)
gayMarriage$Country <- as.factor(gayMarriage$Country)
gayMarriage$Year <- as.integer(gayMarriage$Year)

```

```{r}
# convert rate
marriageRate$Marriage_Rate <- marriageRate$Marriage_Rate * 1000
```


```{r}
# merge all
marriageDF <- merge(marriageRate, gayMarriage, by = c('Country','Year'), all=T)
marriageDF <- merge(marriageDF, births_outside_marriage, by = c('Country','Year'), all=T)
```


```{r}
# visualize missing values
vis_miss(marriageDF)
```

```{r}
sum(is.na(marriageDF$Same_Sex_Marriage))
nrow(marriageDF) - sum(is.na(marriageDF$Same_Sex_Marriage))
```

```{r}
# fill Same_Sex_Marriage column
marriageDF <- marriageDF %>%
  group_by(Country) %>%
  fill(Same_Sex_Marriage) %>%
  fill(Same_Sex_Marriage, .direction = "down")
```

```{r}
#replace NA values in column Same_Sex_Marriage with "not legal"
marriageDF$Same_Sex_Marriage <- marriageDF$Same_Sex_Marriage %>% replace_na('not legal')
```


```{r}
# visualize missing values 
vis_miss(marriageDF)
```

```{r}
# save as csv

write.csv(marriageDF,"first_3_datasets_merged_and_cleaned.csv", row.names = FALSE)
```

